// <auto-generated />
using System;
using BookApi.Models.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookApi.Models.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<int>("PageCount")
                        .HasColumnType("INT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Гарри Поттер",
                            PageCount = 1000,
                            Title = "Гарри Поттер"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Властелин колец",
                            PageCount = 600,
                            Title = "Властелин колец"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Тёмные начала",
                            PageCount = 320,
                            Title = "Тёмные началар"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Убить пересмешника",
                            PageCount = 225,
                            Title = "Убить пересмешника"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Винни Пух",
                            PageCount = 100,
                            Title = "Винни Пух"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1984",
                            PageCount = 300,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Джейн Эйр",
                            PageCount = 400,
                            Title = "Джейн Эйр"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Уловка-22",
                            PageCount = 400,
                            Title = "Уловка-22"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ребекка",
                            PageCount = 410,
                            Title = "Ребекка"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ветер в ивах",
                            PageCount = 440,
                            Title = "Ветер в ивах"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Война и мир",
                            PageCount = 1100,
                            Title = "Война и мир"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Унесённые ветром",
                            PageCount = 550,
                            Title = "Унесённые ветром"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2018, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Эмма",
                            PageCount = 330,
                            Title = "Эмма"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Матильда",
                            PageCount = 430,
                            Title = "Матильда"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Холодный дом",
                            PageCount = 530,
                            Title = "Холодный дом"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2018, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Автостопом по галактике",
                            PageCount = 730,
                            Title = "Автостопом по галактике"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2002, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Дюна",
                            PageCount = 445,
                            Title = "Дюна"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
